# This is a basic workflow to help you get started with Actions

name: 1-building-blocks_v1.yaml

# Controls when the workflow will run
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
                - name: Say hello
                   run: echo "Hello, world!"
  # Allows you to run this workflow manually from the Actions tab
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"

    
