name: 1-building-blocks_v1

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run:
 echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 100
      - name: Say goodbye
        run: echo "Goodbye!"
