name: 1-building-blocks_v1

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0  # This will su the job; if intentional, consider using continue-on-error
      - name: Say goodbye
        run: echo "Goodbye!"
        if: ${{ always() }}  # This ensures it runs even if the previous step fails
